import JSZip from "jszip";

// Raw source imports — copied verbatim into the zip
import componentTokensSource from "../data/componentTokens.js?raw";
import resolveTokenSource from "../utils/resolveToken.js?raw";
import buttonPreviewSource from "../components/previews/ButtonPreview.jsx?raw";
import switchPreviewSource from "../components/previews/SwitchPreview.jsx?raw";
import checkboxPreviewSource from "../components/previews/CheckboxPreview.jsx?raw";
import radioPreviewSource from "../components/previews/RadioPreview.jsx?raw";
import chipPreviewSource from "../components/previews/ChipPreview.jsx?raw";
import tooltipPreviewSource from "../components/previews/TooltipPreview.jsx?raw";
import textInputPreviewSource from "../components/previews/TextInputPreview.jsx?raw";

export async function buildStorybookZip(brands, globalPrimitives) {
  const zip = new JSZip();
  const root = zip.folder("design-system-storybook");

  // --- Copied source files (verbatim) ---
  const src = root.folder("src");
  const data = src.folder("data");
  const utils = src.folder("utils");
  const previews = src.folder("components").folder("previews");

  data.file("componentTokens.js", componentTokensSource);
  utils.file("resolveToken.js", resolveTokenSource);
  previews.file("ButtonPreview.jsx", buttonPreviewSource);
  previews.file("SwitchPreview.jsx", switchPreviewSource);
  previews.file("CheckboxPreview.jsx", checkboxPreviewSource);
  previews.file("RadioPreview.jsx", radioPreviewSource);
  previews.file("ChipPreview.jsx", chipPreviewSource);
  previews.file("TooltipPreview.jsx", tooltipPreviewSource);
  previews.file("TextInputPreview.jsx", textInputPreviewSource);

  // --- Generated brands.js (serialized from current app state) ---
  data.file("brands.js", generateBrandsFile(brands, globalPrimitives));

  // --- Generated story files ---
  const stories = root.folder("stories");
  const defaultBrand = Object.keys(brands)[0] || "theia";

  stories.file("Button.stories.jsx", generateButtonStories(defaultBrand));
  stories.file("Switch.stories.jsx", generateSwitchStories(defaultBrand));
  stories.file("Checkbox.stories.jsx", generateCheckboxStories(defaultBrand));
  stories.file("Radio.stories.jsx", generateRadioStories(defaultBrand));
  stories.file("Chip.stories.jsx", generateChipStories(defaultBrand));
  stories.file("Tooltip.stories.jsx", generateTooltipStories(defaultBrand));
  stories.file("TextInput.stories.jsx", generateTextInputStories(defaultBrand));

  // --- Storybook config ---
  const sbFolder = root.folder(".storybook");
  sbFolder.file("main.js", generateStorybookMain());
  sbFolder.file("preview.jsx", generateStorybookPreview(brands));

  // --- Root config files ---
  root.file("package.json", generatePackageJson());
  root.file("vite.config.js", generateViteConfig());
  root.file("README.md", generateReadme());

  return zip.generateAsync({ type: "blob" });
}

// ---------------------------------------------------------------------------
// Generated file builders
// ---------------------------------------------------------------------------

function generateBrandsFile(brands, globalPrimitives) {
  return `// Auto-generated by Design System Generator
export const GLOBAL_PRIMITIVES = ${JSON.stringify(globalPrimitives, null, 2)};

export const INITIAL_BRANDS = ${JSON.stringify(brands, null, 2)};
`;
}

function generateStorybookMain() {
  return `/** @type { import('@storybook/react-vite').StorybookConfig } */
export default {
  stories: ["../stories/**/*.stories.@(js|jsx)"],
  addons: ["@storybook/addon-essentials"],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
};
`;
}

function generateStorybookPreview(brands) {
  const items = Object.entries(brands)
    .map(([id, brand]) => `      { value: "${id}", title: "${brand.name}" }`)
    .join(",\n");

  const firstBrandId = Object.keys(brands)[0] || "theia";

  return `import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";

export const globalTypes = {
  brand: {
    description: "Brand theme",
    toolbar: {
      title: "Brand",
      icon: "paintbrush",
      items: [
${items}
      ],
      dynamicTitle: true,
    },
  },
};

export const initialGlobals = { brand: "${firstBrandId}" };

export const decorators = [
  (Story) => (
    <MantineProvider>
      <Story />
    </MantineProvider>
  ),
];
`;
}

// ---------------------------------------------------------------------------
// Story generators (CSF3 format)
// ---------------------------------------------------------------------------

function generateButtonStories(defaultBrand) {
  return `import ButtonPreview from "../src/components/previews/ButtonPreview";
import { INITIAL_BRANDS } from "../src/data/brands";

export default {
  title: "Components/Button",
  component: ButtonPreview,
  argTypes: {
    variant: { control: "select", options: ["filled", "outlined", "ghost"] },
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
  },
  args: { variant: "filled", size: "sm" },
  render: (args, { globals }) => (
    <ButtonPreview
      brands={INITIAL_BRANDS}
      brandId={globals.brand || "${defaultBrand}"}
      {...args}
    />
  ),
};

export const Filled = { args: { variant: "filled" } };
export const Outlined = { args: { variant: "outlined" } };
export const Ghost = { args: { variant: "ghost" } };
`;
}

function generateSwitchStories(defaultBrand) {
  return `import SwitchPreview from "../src/components/previews/SwitchPreview";
import { INITIAL_BRANDS } from "../src/data/brands";

export default {
  title: "Components/Switch",
  component: SwitchPreview,
  argTypes: {
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    checked: { control: "boolean" },
    readOnly: { control: "boolean" },
  },
  args: { size: "md", checked: false, readOnly: false },
  render: (args, { globals }) => (
    <SwitchPreview
      brands={INITIAL_BRANDS}
      brandId={globals.brand || "${defaultBrand}"}
      {...args}
    />
  ),
};

export const Unchecked = { args: { checked: false } };
export const Checked = { args: { checked: true } };
`;
}

function generateCheckboxStories(defaultBrand) {
  return `import CheckboxPreview from "../src/components/previews/CheckboxPreview";
import { INITIAL_BRANDS } from "../src/data/brands";

export default {
  title: "Components/Checkbox",
  component: CheckboxPreview,
  argTypes: {
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    checked: { control: "boolean" },
    indeterminate: { control: "boolean" },
    readOnly: { control: "boolean" },
  },
  args: { size: "md", checked: false, indeterminate: false, readOnly: false },
  render: (args, { globals }) => (
    <CheckboxPreview
      brands={INITIAL_BRANDS}
      brandId={globals.brand || "${defaultBrand}"}
      {...args}
    />
  ),
};

export const Unchecked = { args: { checked: false } };
export const Checked = { args: { checked: true } };
export const Indeterminate = { args: { indeterminate: true } };
`;
}

function generateRadioStories(defaultBrand) {
  return `import RadioPreview from "../src/components/previews/RadioPreview";
import { INITIAL_BRANDS } from "../src/data/brands";

export default {
  title: "Components/Radio",
  component: RadioPreview,
  argTypes: {
    variant: { control: "select", options: ["filled", "outline"] },
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    checked: { control: "boolean" },
    readOnly: { control: "boolean" },
    label: { control: "text" },
  },
  args: { variant: "filled", size: "md", checked: true, readOnly: false, label: "Radio option" },
  render: (args, { globals }) => (
    <RadioPreview
      brands={INITIAL_BRANDS}
      brandId={globals.brand || "${defaultBrand}"}
      {...args}
    />
  ),
};

export const Filled = { args: { variant: "filled", checked: true } };
export const Outline = { args: { variant: "outline", checked: true } };
export const Unchecked = { args: { variant: "filled", checked: false } };
`;
}

function generateChipStories(defaultBrand) {
  return `import ChipPreview from "../src/components/previews/ChipPreview";
import { INITIAL_BRANDS } from "../src/data/brands";

export default {
  title: "Components/Chip",
  component: ChipPreview,
  argTypes: {
    variant: { control: "select", options: ["filled", "light", "outline"] },
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    radius: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    checked: { control: "boolean" },
    readOnly: { control: "boolean" },
    label: { control: "text" },
  },
  args: { variant: "filled", size: "sm", radius: "sm", checked: false, readOnly: false, label: "Chip" },
  render: (args, { globals }) => (
    <ChipPreview
      brands={INITIAL_BRANDS}
      brandId={globals.brand || "${defaultBrand}"}
      {...args}
    />
  ),
};

export const FilledUnchecked = { args: { variant: "filled", checked: false } };
export const FilledChecked = { args: { variant: "filled", checked: true } };
export const Light = { args: { variant: "light", checked: true } };
export const Outline = { args: { variant: "outline", checked: true } };
`;
}

function generateTooltipStories(defaultBrand) {
  return `import TooltipPreview from "../src/components/previews/TooltipPreview";
import { INITIAL_BRANDS } from "../src/data/brands";

export default {
  title: "Components/Tooltip",
  component: TooltipPreview,
  argTypes: {
    position: { control: "select", options: ["top", "bottom", "left", "right"] },
    withArrow: { control: "boolean" },
    label: { control: "text" },
    opened: { control: "boolean" },
  },
  args: { position: "top", withArrow: true, label: "Tooltip text", opened: true },
  render: (args, { globals }) => (
    <div style={{ padding: 80, display: "flex", justifyContent: "center" }}>
      <TooltipPreview
        brands={INITIAL_BRANDS}
        brandId={globals.brand || "${defaultBrand}"}
        {...args}
      />
    </div>
  ),
};

export const Top = { args: { position: "top" } };
export const Bottom = { args: { position: "bottom" } };
export const Left = { args: { position: "left" } };
export const Right = { args: { position: "right" } };
`;
}

function generateTextInputStories(defaultBrand) {
  return `import TextInputPreview from "../src/components/previews/TextInputPreview";
import { INITIAL_BRANDS } from "../src/data/brands";

export default {
  title: "Components/TextInput",
  component: TextInputPreview,
  argTypes: {
    variant: { control: "select", options: ["default", "filled"] },
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    radius: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    showLabel: { control: "boolean" },
    labelText: { control: "text" },
    withAsterisk: { control: "boolean" },
    showError: { control: "boolean" },
    errorText: { control: "text" },
    placeholder: { control: "text" },
    disabled: { control: "boolean" },
  },
  args: {
    variant: "default",
    size: "sm",
    radius: "sm",
    showLabel: true,
    labelText: "Label",
    withAsterisk: false,
    showError: false,
    errorText: "Error message",
    placeholder: "Placeholder",
    disabled: false,
  },
  render: (args, { globals }) => (
    <div style={{ maxWidth: 320 }}>
      <TextInputPreview
        brands={INITIAL_BRANDS}
        brandId={globals.brand || "${defaultBrand}"}
        {...args}
      />
    </div>
  ),
};

export const Default = { args: { variant: "default" } };
export const Filled = { args: { variant: "filled" } };
export const WithError = { args: { showError: true, errorText: "This field is required" } };
export const Disabled = { args: { disabled: true } };
export const WithAsterisk = { args: { withAsterisk: true } };
`;
}

// ---------------------------------------------------------------------------
// Root config files
// ---------------------------------------------------------------------------

function generatePackageJson() {
  return JSON.stringify(
    {
      name: "design-system-storybook",
      version: "1.0.0",
      private: true,
      type: "module",
      scripts: {
        storybook: "storybook dev -p 6006",
        "build-storybook": "storybook build",
      },
      dependencies: {
        "@mantine/core": "^8.3.15",
        "@mantine/hooks": "^8.3.15",
        "@emotion/react": "^11.14.0",
        react: "^19.2.0",
        "react-dom": "^19.2.0",
      },
      devDependencies: {
        "@storybook/addon-essentials": "^8.6.0",
        "@storybook/react": "^8.6.0",
        "@storybook/react-vite": "^8.6.0",
        storybook: "^8.6.0",
        "@vitejs/plugin-react": "^4.3.4",
        vite: "^6.2.0",
      },
    },
    null,
    2
  );
}

function generateViteConfig() {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`;
}

function generateReadme() {
  return `# Design System Storybook

Auto-generated by the Design System Generator.

## Getting Started

\`\`\`bash
npm install
npm run storybook
\`\`\`

Storybook will open at http://localhost:6006.

## Brand Switching

Use the **Brand** dropdown in the Storybook toolbar to switch between brand themes.
All components will re-render with the selected brand's tokens.

## Components

- Button (filled, outlined, ghost variants)
- Switch
- Checkbox
- Radio (filled, outline variants)
- Chip (filled, light, outline variants)
- Tooltip
- TextInput (default, filled variants)
`;
}
